# Generated by Django 4.2 on 2023-04-17 18:10

from django.db import migrations, models
import home_gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(null=True)),
                ('main_img', models.ImageField(upload_to=home_gallery.models.upload_gallery_image_path)),
                ('thumbnail', models.ImageField(upload_to=home_gallery.models.upload_gallery_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('facebook', models.SlugField(null=True)),
                ('instagram', models.SlugField(null=True)),
                ('pinterest', models.SlugField(null=True)),
                ('linkedin', models.SlugField(null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
