# Generated by Django 4.2 on 2023-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_gallery', '0002_information_address_information_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='logo',
            field=models.ImageField(null=True, upload_to='core'),
        ),
    ]
