# Generated by Django 4.2 on 2023-04-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_gallery', '0003_information_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='logo_hover',
            field=models.ImageField(null=True, upload_to='core'),
        ),
    ]
