# Generated by Django 4.2 on 2023-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='project-gallery')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.ManyToManyField(null=True, to='projects.resumegallery'),
        ),
    ]
