# Generated by Django 4.2 on 2023-05-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_resumegallery_project_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeGallery',
            new_name='ProjectGallery',
        ),
    ]
