# Generated by Django 4.2 on 2023-05-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_resumegallery_projectgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gallery',
        ),
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectgallery'),
        ),
    ]
