# Generated by Django 4.2 on 2023-05-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_gallery_project_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gallery',
        ),
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.ManyToManyField(to='projects.projectgallery'),
        ),
    ]
