version: '3.9'

services:

  app:
    build: './app'
    container_name: 'app'
    restart: 'always'
    expose:
      - 8000

    volumes:
      - type: 'bind'
        source: './volumes/app'
        target: '/app'
    
  nginx:
    build: './nginx'
    container_name: 'nginx'
    restart: 'always'
    ports:
      - "80:80"
    
    volumes:
      - type: 'bind'
        source: './volumes/media'
        target: '/app/media'

      - type: 'bind'
        source: './volumes/static'
        target: '/app/static'