# Generated by Django 4.2 on 2023-04-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
